import { UserRole } from '@prisma/client';
import { Permission } from './permissions.enum';

const ALL: Permission[] = Object.values(Permission);

// Static role -> permissions matrix. Server-owned; never client-controlled.
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: ALL,
  SYSTEM_ADMIN: [
    Permission.SystemAdmin,
    Permission.AgencyRead,
    Permission.AgencyWrite,
    Permission.AgencyDelete,
    Permission.UserRead,
    Permission.UserWrite,
    Permission.UserDelete,
    Permission.PropertyRead,
    Permission.PropertyWrite,
    Permission.PropertyDelete,
    Permission.UnitRead,
    Permission.UnitWrite,
    Permission.UnitDelete,
    Permission.LeaseRead,
    Permission.LeaseWrite,
    Permission.LeaseDelete,
    Permission.TenantRead,
    Permission.TenantWrite,
    Permission.TenantDelete,
    Permission.OwnerRead,
    Permission.OwnerWrite,
    Permission.OwnerDelete,
    Permission.RentScheduleRead,
    Permission.RentScheduleWrite,
    Permission.RentScheduleDelete,
    Permission.PaymentRead,
    Permission.PaymentWrite,
    Permission.PaymentDelete,
  ],
  AGENCY_OWNER: [
    Permission.AgencyRead,
    Permission.AgencyWrite,
    Permission.AgencyDelete,
    Permission.UserRead,
    Permission.UserWrite,
    Permission.PropertyRead,
    Permission.PropertyWrite,
    Permission.PropertyDelete,
    Permission.UnitRead,
    Permission.UnitWrite,
    Permission.UnitDelete,
    Permission.LeaseRead,
    Permission.LeaseWrite,
    Permission.LeaseDelete,
    Permission.TenantRead,
    Permission.TenantWrite,
    Permission.TenantDelete,
    Permission.OwnerRead,
    Permission.OwnerWrite,
    Permission.OwnerDelete,
    Permission.RentScheduleRead,
    Permission.RentScheduleWrite,
    Permission.RentScheduleDelete,
    Permission.PaymentRead,
    Permission.PaymentWrite,
    Permission.PaymentDelete,
  ],
  AGENCY_STAFF: [
    Permission.AgencyRead,
    Permission.UserRead,
    Permission.PropertyRead,
    Permission.PropertyWrite,
    Permission.UnitRead,
    Permission.LeaseRead,
    Permission.TenantRead,
    Permission.TenantWrite,
    Permission.OwnerRead,
    Permission.OwnerWrite,
    Permission.RentScheduleRead,
    Permission.PaymentRead,
    Permission.PaymentWrite,
  ],
  AGENT: [
    Permission.AgencyRead,
    Permission.UserRead,
    Permission.PropertyRead,
    Permission.UnitRead,
    Permission.LeaseRead,
    Permission.TenantRead,
    Permission.OwnerRead,
    Permission.RentScheduleRead,
    Permission.PaymentRead,
  ],
  VIEWER: [
    Permission.AgencyRead,
    Permission.UserRead,
    Permission.PropertyRead,
    Permission.UnitRead,
    Permission.LeaseRead,
    Permission.TenantRead,
    Permission.OwnerRead,
    Permission.RentScheduleRead,
    Permission.PaymentRead,
  ],
};

export function permissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}
