// Logical permissions (internal only — no DB). Resource.action format.
export enum Permission {
  AgencyRead = 'agency.read',
  AgencyWrite = 'agency.write',
  AgencyDelete = 'agency.delete',
  UserRead = 'user.read',
  UserWrite = 'user.write',
  UserDelete = 'user.delete',
  PropertyRead = 'property.read',
  PropertyWrite = 'property.write',
  PropertyDelete = 'property.delete',
  UnitRead = 'unit.read',
  UnitWrite = 'unit.write',
  UnitDelete = 'unit.delete',
  LeaseRead = 'lease.read',
  LeaseWrite = 'lease.write',
  LeaseDelete = 'lease.delete',
  TenantRead = 'tenant.read',
  TenantWrite = 'tenant.write',
  TenantDelete = 'tenant.delete',
  OwnerRead = 'owner.read',
  OwnerWrite = 'owner.write',
  OwnerDelete = 'owner.delete',
  RentScheduleRead = 'rent_schedule.read',
  RentScheduleWrite = 'rent_schedule.write',
  RentScheduleDelete = 'rent_schedule.delete',
  PaymentRead = 'payment.read',
  PaymentWrite = 'payment.write',
  PaymentDelete = 'payment.delete',
  SystemAdmin = 'system.admin',
  BillingManage = 'billing.manage',
}
